services:
  # Backend API service
  - type: web
    name: projectvidy-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://projectvidy-frontend.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend static site
  - type: static
    name: projectvidy-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://projectvidy-backend.onrender.com/api
      - key: VITE_CLOUD_NAME
        value: dvsuv18xd
      - key: VITE_UPLOAD_PRESET
        value: myecom 